ctmc_lectures/poisson.md

Hi @jstac , this PR corrected a fact used in lecture ``poisson``, please find [here](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/poisson.md#uniqueness) (the 7th sentence above subsection **Uniqueness**), from
- ``Using the fact that $kh = t_k \approx t$ when $k$ is large``
to 
- ``Using the fact that $kh = t_k \approx t$ as $h \to 0$``,
aligned with the statement of this fact in lecture ``memoryless``, please find [here](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/memoryless.md#from-geometric-to-exponential).

pos3_correction

---

ctmc_lectures/memoryless.md

Good afternoon, @jstac . This PR corrects an error in the proof of uniquely memoryless feature of the exponential distribution in lecture ``memoryless``, please see [here](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/memoryless.md#memoryless-property-of-the-exponential-distribution).
This is because
- ``Property 1`` states ``f is decreasing on \mathbb R_+``,
- you assume that ``a_n \leq t \leq b_n``,
then in the last several sentences of the proof, we should have 
- ``f(b_n) \leq f(t) \leq f(a_n)`` instead of ``f(a_n) \leq f(t) \leq f(b_n)`` and
- ``f(1)^{b_n} \leq f(t) \leq f(1)^{a_n}`` instead of ``f(1)^{a_n} \leq f(t) \leq f(1)^{b_n}``
This PR corrects this mistake.
Btw, @jstac , do you think we should add a symbol ``\square`` or ``\blacksquare`` at the end of …

md1_issue_in_proof

---

ctmc_lectures/memoryless.md

Good afternoon, @jstac . This PR adds an expression ``$X > s-t$ if and only if $Y > s-t$. We get`` to the second case of solution 1 in lecture [memoryless](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/memoryless.md#solution-to-exercise-1).
I add it because I find the second case only holds when $t<s$, which is not specified in the proof.
Do you think it is an issue? 
If so, do you like the modification or another one we can add the condition ``$t < s$`` or else?

md2_a_possible_improvement_solution1

---

ctmc_lectures/markov_prop.md

Hi, @jstac , this PR corrects a typo in equation (13) (or equivalent, equation jointdeq) in subsection ``The Joint Distribution`` of lecture [markov_prop](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#the-joint-distribution):
- the ``k`` in expression ``\PP\{ X_{t_1} = y_1, \ldots, X_{t_k} = y_k \}`` should be ``m``, according to contexts.

mp3_typos_in_math

---

ctmc_lectures/markov_prop.md

Hi @jstac , this PR updates the link attached to the recall part in lecture [markov_prop](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#discrete-time-finite-state):
- from the lecture [finite_markov](https://python.quantecon.org/finite_markov.html) to [subsection Marginal Distribution of that lecture](https://python.quantecon.org/finite_markov.html#Marginal-Distributions), that is, the specific place with this recalled statement.

mp4_update_link

---

ctmc_lectures/markov_prop.md

Good evening, @jstac , this PR rephrases ``that the`` as ``its`` in the follow sentence of lecture [markov_prop](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md):
- ``A continuous time stochastic process is said to have the Markov property if
that the past and future are independent given the current state.``

mp5_minor_edit

---

ctmc_lectures/markov_prop.md

Hi @jstac , this PR adds a link (https://en.wikipedia.org/wiki/Finite-dimensional_distribution) to clarify ``finite-dimensional distributions`` in subsection [The Continuous Time Case](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#the-continuous-time-case) of markov_prop.

mp9_clarify_finite_dimensiional_distributions

---

ctmc_lectures/markov_prop.md

Hi @jstac , this PR adds a wiki link (https://en.wikipedia.org/wiki/Functional_(mathematics)) to clarify ``point evaluation functional`` in subsection [The Canonical Chain](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#the-canonical-chain) of ``markov_prop``.

mp10_clarify_functional

---

ctmc_lectures/markov_prop.md

Good morning @jstac , this PR corrects ``E`` as ``\Exp`` to make the notations for the exponential distribution consistent in [markov_prop](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#a-model-of-inventory-dynamics). (The commit ``mp11_typo`` belongs to last PR and I reverted it here.)
Do you think it is a good idea to change all notations for the exponential distributions to ``\Exp`` in all following lectures?

mp12_E->\Exp

---

ctmc_lectures/markov_prop.md

Hi @jstac , this PR adds a missing summation notation, ``\sum_{k \geq 0}``,  in the RHS of the second equality of the following math expression in subsection [markov-property-1](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#markov-property-1) of lecture ``markov_prop``:
- ``\PP\{X_{s + t} = y \,|\, \fF_s \}
= \sum_{k \geq 0}
K^k(Y_{N_s}, y) \frac{(t \lambda )^k}{k!} e^{-t \lambda}
= K^k(X_s, y) \frac{(t \lambda )^k}{k!} e^{-t \lambda}``

mp13_add_summation

---

ctmc_lectures/markov_prop.md

Good morning @jstac , this PR changes ``P^t`` to ``P_t`` in subsection [Transition Semigroup](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#transition-semigroup) of markov_prop to make notations consistent with those in Markov property.

mp14_P^t->P_t

---

ctmc_lectures/markov_prop.md

Good morning @jstac , this PR corrects some errors in the proof of [Exercise 3](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#solution-to-exercise-3) of lecture markov_prop:
- ``P (x_{n-1}, x_n ) \mathbf P_\psi^n(x_0, x_1, \ldots, x_{n-1}) =
P (x_n, x_{n+1} )
\psi(x_0)
P(x_0, x_1)
\times \cdots \times
P(x_{n-1}, x_{n-1})`` --->>>
- ``P (x_{n-1}, x_n ) \mathbf P_\psi^{n-1}(x_0, x_1, \ldots, x_{n-1}) =
P (x_{n-1}, x_n )
\psi(x_0)
P(x_0, x_1)
\times \cdots \times
P(x_{n-2}, x_{n-1})``

mp18_correct_proof_ex3

---

ctmc_lectures/markov_prop.md

Hi @jstac , this PR deletes a redundant full stop in the following sentence of [Exercise 4](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#exercise-4) of lecture markov_prop:
- ``Try to produce your own version of the figure {ref}`flow_fig`.``
The full stop is included in the figure reference, please see [here](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#distribution-flows-for-the-inventory-model).

mp17_delete_redundant_full_stop

---

ctmc_lectures/markov_prop.md

Hi @jstac , this PR adds ``as $M \to \infty, $`` in the following sentence to clarify the limit condition of the equation in subsection [distribution-flows-for-the-inventory-model](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md#distribution-flows-for-the-inventory-model) in lecture markov_prop:
- ``Then $\hat \psi_t(x)$ will be close to $\PP\{X_t = x\}$ by the law of large numbers.``

mp16_clarify_the_limit

---

ctmc_lectures/kolmogorov_bwd.md

Hi @jstac , this PR makes two lowercase letters uppercase, consistent with other lines in lists of subsection [state-dependent-jump-intensities](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_bwd.md#state-dependent-jump-intensities) of lecture komogorov_bwd:
- ``draw`` -> ``Draw``,
- ``use`` -> ``Use``

kbe3_consistent_uppercase

---

ctmc_lectures/kolmogorov_bwd.md

Hi @jstac , this PR modifies the title of lecture [kolmogorov_bwd](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_bwd.md) as ``The Kolmogorov Backward Equation``, aligned with the title of lecture [kolmogorov_bwd](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_fwd.md), ``The Kolmogorov Forward Equation``.

kbe6_title_consistent

---

ctmc_lectures/kolmogorov_bwd.md

Good evening, @jstac , this PR corrects some errors in the [proof of Lemma 7](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_bwd.md#an-integral-equation) in lecture komogorov_bwd:
- ``>`` -> ``\leq``

kbe4_issue_proof

---

ctmc_lectures/kolmogorov_fwd.md

Hi @jstac , this PR corrects the following typos in subsection [Matrix- vs Vector-Valued ODEs](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_fwd.md#matrix--vs-vector-valued-odes) of lecture kolmogorov_fwd:
- ``And matrices are really maps, that send vectors into vectors.`` -> ``And matrices are really maps, which send vectors into vectors.``,
- ``But, in the end, the object that we want to describe is a the Markov`` -> ``But, in the end, the object that we want to describe is a Markov``.

kfe2_typos

---

ctmc_lectures/kolmogorov_bwd.md

Hi @jstac , this PR corrects two possible minor typos in lecture [kolmogorov_bwd](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_bwd.md#overview):
- ``This assumption was made purely for convenience and seems unlikely to hold true.`` -->> ``This assumption was made purely for convenience and seemed unlikely to hold true.``
- ``Next we check positivity of all elements of P_t (which can easily fail for`` -> ``Next we check nonnegativity of all elements of P_t (which can easily fail for``

kbe2_minor_typo

---

ctmc_lectures/kolmogorov_fwd.md

Hi @jstac , this PR adds the following wiki link to clarify ``unit simplex`` in the subsection [Review of the Discrete Time Case](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_fwd.md#review-of-the-discrete-time-case) of lecture kolmogorov_fwd:
- https://en.wikipedia.org/wiki/Simplex

kfe1_clarify_unit_simplex

---

ctmc_lectures/kolmogorov_bwd.md

Hi @jstac , this PR adds the following sentence to clarify column-vector-of-ones ``1`` in the [proof of lemma 9 of lecture kolmogorov_bwd](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_bwd.md#checking-the-transition-semigroup-properties):
- ``with $1$
as a column vector of ones``.
@jstac , I noticed that you use the same notations for a real number ``1`` and a column-vector-of-ones ``1`` in this lecture and the following lectures.
Do you think we should use another notation to clarify the column-vector-of-ones to distinguish these two?

kbe7_clarify_vector_1

---

ctmc_lectures/kolmogorov_bwd.md

Hi @jstac , this PR adjusts the label fontsize of 2 figures' x-axis in lecture [komogorov_bwd](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_bwd.md#an-integral-equation) and sets it to ``14``:
- ``ax.set(xlabel="inventory")`` -> ``ax.set_xlabel("inventory", fontsize=14)``

kbe5_adjust_fontsize_of_figure's_xaxis

---

ctmc_lectures/kolmogorov_fwd.md

Hi @jstac , this PR corrects the following errors in [exercises of lecture kolmogorov_fwd](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/kolmogorov_fwd.md#exercises):
- ``\downarrow`` -> ``\to``,
- ``gives`` -> ``give``,
- ``a intensity matrix`` -> ``an intensity matrix``.

kfe4_issues_exercises

---

ctmc_lectures/ergodicity.md

Good afternoon, @jstac , this PR corrects following typos in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md):
- ``help line`` -> ``helpline``,
- ``Asymptotic Stabiltiy`` -> ``Asymptotic Stabilitiy``

se1_typos1

---

ctmc_lectures/uc_mc_semigroups.md

Good day, @jstac , this PR corrects following typos in lecture [us_mc_semigroup](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md):
- ``matricies`` -> ``matrices``,
- ``charcterization`` -> ``characterization``,
- ``a intensity matrix`` -> ``an intensity matrix``,
- ``first along the principle diagonal`` -> ``first along with the principle diagonal``,
- ``contably infinite`` -> ``countably infinite``

ucms1_typos1

---

ctmc_lectures/generators.md

Good morning, @jstac , this PR adds a wiki link (https://en.wikipedia.org/wiki/Banach_space) to clarify the first-appearing ``Banach spaces`` in lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md).

[generators]2_clarify_banach_space

---

ctmc_lectures/generators.md

Dear @jstac , this PR relocates the wiki link (https://en.wikipedia.org/wiki/Operator_norm), which originally clarified ``is a norm``, to clarify ``operator norm`` in lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md).

[generators]3_relocate_clarification

---

ctmc_lectures/generators.md

Hi @jstac , this PR adds the following necessary condition in the assumption part of proofs in solution 2 & 3 of lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md).:
- ``A is not bounded`` -->> ``A may be not bounded``:
- ``as $n \to \infty$``
The original assumption parts of these proofs ignore this condition, which is required in the following parts.

[generators]6_add_necessary_condition_in_solution2_and_3

---

ctmc_lectures/generators.md

Good morning @jstac , this PR deletes a problematic `` ``(space) in a math expression in solution 3 of lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md#solutions).
This space would make the latex math expression unable to be compiled.

[generators]7_delete_a_problematic_space

---

ctmc_lectures/generators.md

Good day @jstac , this PR adds a pair of brackets ``()`` to the notation of semigroup ``$P_t$`` to make it consistent with all other semigroup notations in lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md).

[generators]8_keep_semigroup_notation_consistent

---

ctmc_lectures/generators.md

Hi @jstac , this PR makes the following change in lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md):
- ``A is not bounded`` -->> ``A may be not bounded``
The original tone can be too strong in the context.

[generators]5_rephrase

---

ctmc_lectures/generators.md

Hi @jstac , this PR corrects the following possible typo in lecture [generators](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/generators.md):
- ``\lL(\ell_1)``(L(l_1)) -->> ``\linop`` (L(B))
Even if ``\lL(\ell_1)`` is correct here, since it appears without defining first (we define ``\lL(\ell_1)`` in the next lecture [uc_mc_semigroups](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md)), we'd better add a clarification.

[generators]10_correct_or_clarify

---

ctmc_lectures/uc_mc_semigroups.md

Dear @jstac , this PR corrects following possible typos in lecture [uc_mc_semigroups](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md):
- ``$\dD$, the set of distributions on $S$`` -->> ``$\dD$, the set of all distributions on $S$``,
- ``We need only show that $Q$ is a conservative intensity matrix.`` -->>  ``We only need to show that $Q$ is a conservative intensity matrix.``,
- ``intenintensity matrices`` -->> ``intensity matrices``
More PRs are coming.

[uc_mc_semigroups]1_typos2

---

ctmc_lectures/uc_mc_semigroups.md

Dear @jstac , this PR corrects an error in the following sentence of lecture [uc_mc_semigroups](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md):
- ``the family $(P_t)$ in $\lL(\ell_1)$ defined by $P_t = e^{tQ}$ defines a UC Markov semigroup on $S$``
where ``$S$`` should be ``$\ell_1$`` according to the contexts.

[uc_mc_semigroups]2_error_above_theorem17

---

ctmc_lectures/uc_mc_semigroups.md

Hi @jstac , this PR adds missing ``-`` signs for some math expressions in ``Example 18`` (The example above subsection ``A Necessary and Sufficient Condition`` of lecture [uc_mc_semigroups](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md).
The error comes from a derivation:
- ``e^{\lambda t (K-I)} = e^{\lambda t} e^{\lambda t K}``
where ``e^{\lambda t}`` should be ``e^{-\lambda t}``.

[uc_mc_semigroups]3_missing_minus_sign_in_math_example18

---

ctmc_lectures/uc_mc_semigroups.md

Dear @jstac , this PR adds all missing ``=`` for the last math expression in ``Solution 1`` of lecture [uc_mc_semigroups](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md).

[uc_mc_semigroups]5_add_missing_equality_signs_in_solution1

---

ctmc_lectures/uc_mc_semigroups.md

Hi @jstac , this PR corrects errors in the following math expression of lecture [uc_mc_semigroups](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md)'s ``Solution 4``:
- ``K^{m+1}(i, j) = \sum_n K(i, n) K^m (n, j) = \sum_n K(i, n) \mathbb 1\{j = i + m\} = K(i, m-j)`` -->> ``K^{m+1}(i, j) = \sum_n K(i, n) K^m (n, j) = \sum_n K(i, n) \mathbb 1\{j = n + m\} = K(i, j-m)``

[uc_mc_semigroups]6_correct_errors_in_solution4

---

ctmc_lectures/ergodicity.md

Good afternoon, @jstac , this PR adds ``$(P_t)$`` after ``a Markov semigroup`` to clarify it in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md).

[ergodicity]2_add_(P_t)

---

ctmc_lectures/ergodicity.md

Hi @jstac , this PR makes following changes to clarify one-side limit, aligned with your previous notation, in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md):
- ``$t \to 0$`` -->> ``$t \to 0^+$``,
- ``$\| \psi Q \| \leq \liminf_{t \to 0} \| \psi D_t \|$`` -->> ``$\| \psi Q \| \leq \liminf_{t \downarrow 0} \| \psi D_t \|$``

[ergodicity]5_clarify_side_limit

---

ctmc_lectures/ergodicity.md

Hi @jstac , this PR makes the following change to clarify states x and y in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md):
- ``Let $(P_t)$ be a Markov semigroup on $S$.`` -->> ``Let $(P_t)$ be a Markov semigroup on $S$ and consider arbitrary states $x, y \in S$.``

[ergodicity]6_clarify_states_x_y_in_S

---

ctmc_lectures/ergodicity.md

Dear @jstac , this PR adds a wiki link (https://en.wikipedia.org/wiki/Absorbing_set) to clarify ``absorbing set`` in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md).

[ergodicity]7_clarify_absorbing_set

---

ctmc_lectures/ergodicity.md

Dear @jstac , for solution 2 of lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md), this PR corrects a mistake and adds a condition to clarify its holding:
- $(\phi Q)(j) = \sum_{i \geq 0} \phi(i) Q(i, j) = - \lambda_j \phi(j) + \lambda_{j} \phi(j) = 0$ -->> $(\phi Q)(j) = \sum_{i \geq 0} \phi(i) Q(i, j) = - \lambda_j \phi(j) + \lambda_{j-1} \phi(j-1) = 0$
- ``Then`` -->> ``Then, for any $j \geq 1$,``
Note that $\phi Q$ is a forward equation and because of the [definition](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md#exercises) of ``Q``, we have the corrected math expression above.
However, this brings us a new issue that the statement after this math expression, ``It follows that $\phi$ is …

[ergodicity]11_error_in_solution2 (More Discussion Required)

---

ctmc_lectures/ergodicity.md

Hi @jstac , this PR 
- deletes an unnecessary ``.`` in the math expression ``\| \psi P_t - \psi^* \|= \| \psi P_{sn} P_h - \psi^* P_h \| \leq \| \psi P_{sn} - \psi^* \| < \epsilon``
- changes ``Hence asymptotic stability holds`` -->> ``Hence asymptotic stability holds for $(P_t)$.``
in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md).

[ergodicity]8_fix_full_stop_issues

---

ctmc_lectures/ergodicity.md

Hi @jstac , this PR changes ``$v(i) =
i$`` to ``$v(j) =
j$``, aligned with its following math expressions in lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md).

[ergodicity]9_modify_v(i)_to_v(j)

---

ctmc_lectures/ergodicity.md

Good afternoon, @jstac , this PR makes the following change in [example 31 of ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md#stability-via-drift):
- ``Setting $F=\{0\}$ and $\epsilon = \mu - \lambda$`` -->> ``Setting $F=\{0\}$ and $M = \lambda - \mu = - \epsilon$``
It seems that the origin contexts do not specify the condition for $M$, which is needed when using Theorem 30.

[ergodicity]10_add_condition_for_M

---

ctmc_lectures/ergodicity.md

Dear @jstac , thanks for the inspiring talk and really nice discussions with me.
As we discussed, for lecture [ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md#solution-to-exercise-2), this PR adds ``non-increasing`` condition on $(\lambda_k)$ 
- "Let $(\lambda_k)$ be a bounded sequence in $(0, \infty)$." -->> "Let $(\lambda_k)$ be a bounded non-increasing sequence in $(0, \infty)$." 
and corrects the solution to exercise 2 as:
"Suppose to the contrary that $\phi \in \dD$ and $\phi Q = 0$.
Then, for any $j \geq 1$,
$$ (\phi Q)(j) = \sum_{i \geq 0} \phi(i) Q(i, j) = - \lambda_j \phi(j) + \lambda_{j-1} \phi(j-1) = 0$$
Since $(\lambda_k)$ is non-increasing, it follows that
$$ \frac{\phi(j)}{\phi(j-1)} = \frac{\lambda_{j-1}}{\lambda_j} \geq 1 $$ …

[ergodicity]fix_proof_ex2

---

ctmc_lectures/markov_prop.md
ctmc_lectures/uc_mc_semigroups.md

Hi @jstac , there is an undefined label ``prob_view`` intending to link to an unknown lecture (according to contexts, it can be lecture ``uc_mc_semigroup``.
This PR 
- labels the lecture [uc_mc_semigroup](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/uc_mc_semigroups.md) by ``ucmc``,
- changes the label ``prob_view`` in lecture [markov_prop](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/markov_prop.md) to ``ucmc``.

[markov_prop]&[uc_mc_semigroup]correct an undefined label

---

ctmc_lectures/_config.yml
ctmc_lectures/ergodicity.md
ctmc_lectures/generators.md
ctmc_lectures/kolmogorov_bwd.md
ctmc_lectures/kolmogorov_fwd.md
ctmc_lectures/markov_prop.md
ctmc_lectures/memoryless.md
ctmc_lectures/poisson.md
ctmc_lectures/uc_mc_semigroups.md

This PR enables `sphinx-exercise` and migrates to use the directives `exercise` and `solution`:
**HTML:**
**LaTeX:**

ENH: enable sphinx-exercise and migrate exercise text

---

environment.yml

This includes a fix for linking to github rather than documents within github for `View Source`

ENH: update to quantecon-book-theme==0.7.6

---

.github/workflows/linkcheck.yml
lectures/kolmogorov_fwd.md
lectures/markov_prop.md

This PR enables the sphinx link checker

ENH: add linkchecker

---

.github/workflows/cache.yml
.github/workflows/ci.yml
.github/workflows/linkcheck.yml
.github/workflows/publish.yml
environment.yml

This PR:
- upgrades `anaconda=2025.06`
- python=3.13
This includes upgrades to `jb==1.04post1` and the latest `sphinx-tojupyter`, `quantecon-book-theme` etc.

ENH: Upgrade software anaconda=2025.06, and python=3.13
